export enum AdminTypes {
    Admin = 1,
    Supporter,
    PlastMember,
    PlastHead,
    EventAdministrator,
    KurinHead,
    KurinSecretary,
    OkrugaHead,
    OkrugaSecretary,
    CityHead,
    CitySecretary,
    FormerPlastMember,
    RegisteredUser,
    Interested,
    CityHeadDeputy,
    OkrugaHeadDeputy,
    KurinHeadDeputy,
    RegionBoardHead,
    GoverningBodyAdmin,
    GoverningBodyHead,
    GoverningBodySecretary,
    GoverningBodySectorHead,
    GoverningBodySectorSecretary,
  }
  