enum UkraineOblasts {
    NotSpecified = 0,
    Cherkasy,
    Chernihiv,
    Chernivtsi,
    Crimea,
    Dnipropetrovsk,
    Donetsk,
    IvanoFrankivsk,
    Kharkiv,
    Kherson,
    Khmelnytskyi,
    Kyiv,
    Kirovohrad,
    Luhansk,
    Lviv,
    Mykolaiv,
    Odessa,
    Poltava,
    Rivne,
    Sumy,
    Ternopil,
    Vinnytsia,
    Volyn,
    Zakarpattia,
    Zaporizhzhia,
    Zhytomyr
}

export default UkraineOblasts;