export enum Roles {
  Admin = "Admin",
  Supporter = "Прихильник",
  PlastMember = "Дійсний член організації",
  PlastHead = "Голова Пласту",
  EventAdministrator = "Адміністратор подій",
  KurinHead = "Голова Куреня",
  KurinHeadDeputy = "Заступник Голови Куреня",
  KurinSecretary = "Діловод Куреня",
  OkrugaHead = "Голова Округи",
  OkrugaHeadDeputy = "Заступник Голови Округи",
  OkrugaSecretary = "Діловод Округи",
  CityHead = "Голова Станиці",
  CityHeadDeputy = "Заступник Голови Станиці",
  CitySecretary = "Діловод Станиці",
  FormerPlastMember = "Колишній член Пласту",
  RegisteredUser = "Зареєстрований користувач",
  Interested = "Зацікавлений",
  RegionBoardHead = "Голова Краю",
  GoverningBodyHead = "Голова Керівного Органу",
  GoverningBodySecretary = "Діловод Керівного Органу",
  GoverningBodySectorHead = "Голова Напряму Керівного Органу",
  GoverningBodySectorSecretary = "Діловод Напряму Керівного Органу",
}
