const rawData = [
  {
    Name: "Wyatt Downs",
    Company: "Bibendum LLC",
    Email: "neque@faucibuslectusa.edu",
    City: "Sesto Campano",
    Salary: "9,910",
    Enable: "False",
    EnterDate: "2019/08/17",
    Personal: "16610223 6277",
  },
  {
    Name: "Bradley Valencia",
    Company: "Massa Inc.",
    Email: "Nunc@scelerisquenequeNullam.com",
    City: "Gembloux",
    Salary: "8,009",
    Enable: "True",
    EnterDate: "2019/09/19",
    Personal: "16101217 8073",
  },
  {
    Name: "Elton Cantrell",
    Company: "Et Associates",
    Email: "Aenean.eget@lacus.edu",
    City: "Serralunga d'Alba",
    Salary: "9,217",
    Enable: "False",
    EnterDate: "2020/03/05",
    Personal: "16430725 2801",
  },
  {
    Name: "Sylvester Burton",
    Company: "Nulla Eget Limited",
    Email: "sit.amet.metus@metusInlorem.ca",
    City: "Leipzig",
    Salary: "9,592",
    Enable: "True",
    EnterDate: "2020/03/17",
    Personal: "16541011 2873",
  },
  {
    Name: "Nathaniel Glover",
    Company: "Erat Nonummy Institute",
    Email: "lectus.ante.dictum@iaculisneceleifend.net",
    City: "Broken Hill",
    Salary: "7,122",
    Enable: "True",
    EnterDate: "2019/05/31",
    Personal: "16450310 9318",
  },
  {
    Name: "Dylan Strong",
    Company: "Velit Cras Inc.",
    Email: "vestibulum.lorem.sit@feugiatmetussit.org",
    City: "Albagiara",
    Salary: "7,128",
    Enable: "False",
    EnterDate: "2019/05/03",
    Personal: "16260812 9942",
  },
  {
    Name: "Hamilton Craig",
    Company: "Phasellus Dapibus Quam Incorporated",
    Email: "Mauris.molestie.pharetra@pretiumaliquet.org",
    City: "Cefalà Diana",
    Salary: "8,505",
    Enable: "False",
    EnterDate: "2020/12/20",
    Personal: "16480424 0416",
  },
  {
    Name: "Samson Richardson",
    Company: "Morbi Limited",
    Email: "orci@litoratorquentper.net",
    City: "Schwäbisch Gmünd",
    Salary: "8,065",
    Enable: "True",
    EnterDate: "2019/09/08",
    Personal: "16720601 5476",
  },
];
export default rawData;
